// Unified EVM Chain Registry
// Superset of all chains across all providers.
// Provider-specific keys use namespace prefixing (e.g., moralisChainSlug, etherscanAlias).
// Missing key = provider does not support this chain.

const EVM_CHAINS = [
    // ============================================================
    // MAINNETS
    // ============================================================
    {
        alias: 'ETHEREUM_MAINNET',
        chainId: 1,
        name: 'Ethereum Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        etherscanAlias: 'ETHEREUM_MAINNET',
        etherscanChainId: 1,
        simduneAlias: 'ETHEREUM_MAINNET',
        simduneChainId: 1,
        simduneChainSlug: 'ethereum',
        moralisChainSlug: 'eth',
        moralisChainHex: '0x1',
        blocknativeAlias: 'ETHEREUM_MAINNET',
        blocknativeChainId: 1,
        infuraSubdomain: 'mainnet',
        alchemyNetworkSlug: 'eth-mainnet',
        goldrushChainSlug: 'ETH_MAINNET',
        theGraphSlug: 'ethereum'
    },
    {
        alias: 'POLYGON_MAINNET',
        chainId: 137,
        name: 'Polygon Mainnet',
        isTestnet: false,
        nativeCurrency: 'POL',
        etherscanAlias: 'POLYGON_MAINNET',
        etherscanChainId: 137,
        simduneAlias: 'POLYGON_MAINNET',
        simduneChainId: 137,
        simduneChainSlug: 'polygon',
        moralisChainSlug: 'polygon',
        moralisChainHex: '0x89',
        blocknativeAlias: 'POLYGON_MAINNET',
        blocknativeChainId: 137,
        infuraSubdomain: 'polygon-mainnet',
        alchemyNetworkSlug: 'polygon-mainnet',
        theGraphSlug: 'polygon'
    },
    {
        alias: 'ARBITRUM_ONE_MAINNET',
        chainId: 42161,
        name: 'Arbitrum One Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        etherscanAlias: 'ARBITRUM_ONE_MAINNET',
        etherscanChainId: 42161,
        simduneAlias: 'ARBITRUM_ONE',
        simduneChainId: 42161,
        simduneChainSlug: 'arbitrum',
        moralisChainSlug: 'arbitrum',
        moralisChainHex: '0xa4b1',
        blocknativeAlias: 'ARBITRUM_ONE',
        blocknativeChainId: 42161,
        infuraSubdomain: 'arbitrum-mainnet',
        alchemyNetworkSlug: 'arb-mainnet',
        theGraphSlug: 'arbitrum'
    },
    {
        alias: 'OPTIMISM_MAINNET',
        chainId: 10,
        name: 'OP Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        etherscanAlias: 'OPTIMISN_MAINNET',
        etherscanChainId: 10,
        simduneAlias: 'OPTIMISM_MAINNET',
        simduneChainId: 10,
        simduneChainSlug: 'optimism',
        moralisChainSlug: 'optimism',
        moralisChainHex: '0xa',
        blocknativeAlias: 'OPTIMISN_MAINNET',
        blocknativeChainId: 10,
        infuraSubdomain: 'optimism-mainnet',
        alchemyNetworkSlug: 'opt-mainnet',
        theGraphSlug: 'optimism'
    },
    {
        alias: 'BASE_MAINNET',
        chainId: 8453,
        name: 'Base Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        etherscanAlias: 'BASE_MAINNET',
        etherscanChainId: 8453,
        simduneAlias: 'BASE_MAINNET',
        simduneChainId: 8453,
        simduneChainSlug: 'base',
        moralisChainSlug: 'base',
        moralisChainHex: '0x2105',
        blocknativeAlias: 'BASE',
        blocknativeChainId: 8453,
        infuraSubdomain: 'base-mainnet',
        alchemyNetworkSlug: 'base-mainnet',
        goldrushChainSlug: 'BASE_MAINNET',
        theGraphSlug: 'base'
    },
    {
        alias: 'BINANCE_MAINNET',
        chainId: 56,
        name: 'BNB Smart Chain Mainnet',
        isTestnet: false,
        nativeCurrency: 'BNB',
        etherscanAlias: 'BINANCE_MAINNET',
        etherscanChainId: 56,
        simduneAlias: 'BNB_CHAIN',
        simduneChainId: 56,
        simduneChainSlug: 'bnb',
        moralisChainSlug: 'bsc',
        moralisChainHex: '0x38',
        blocknativeAlias: 'BINANCE_MAINNET',
        blocknativeChainId: 56,
        infuraSubdomain: 'bsc-mainnet',
        alchemyNetworkSlug: 'bnb-mainnet',
        goldrushChainSlug: 'BSC_MAINNET',
        theGraphSlug: 'bsc'
    },
    {
        alias: 'AVALANCHE_MAINNET',
        chainId: 43114,
        name: 'Avalanche C-Chain',
        isTestnet: false,
        nativeCurrency: 'AVAX',
        etherscanAlias: 'AVALANCHE_CCHAIN',
        etherscanChainId: 43114,
        simduneAlias: 'AVALANCHE_CCHAIN',
        simduneChainId: 43114,
        simduneChainSlug: 'avalanche_c',
        moralisChainSlug: 'avalanche',
        moralisChainHex: '0xa86a',
        blocknativeAlias: 'AVALANCHE',
        blocknativeChainId: 43114,
        infuraSubdomain: 'avalanche-mainnet',
        alchemyNetworkSlug: 'avax-mainnet',
        theGraphSlug: 'avalanche'
    },
    {
        alias: 'LINEA_MAINNET',
        chainId: 59144,
        name: 'Linea Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        etherscanAlias: 'LINEA_MAINNET',
        etherscanChainId: 59144,
        simduneAlias: 'LINEA_MAINNET',
        simduneChainId: 59144,
        simduneChainSlug: 'linea',
        moralisChainSlug: 'linea',
        moralisChainHex: '0xe708',
        blocknativeAlias: 'LINEA_MAINNET',
        blocknativeChainId: 59144,
        infuraSubdomain: 'linea-mainnet',
        alchemyNetworkSlug: 'linea-mainnet'
    },
    {
        alias: 'SCROLL_MAINNET',
        chainId: 534352,
        name: 'Scroll Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        etherscanAlias: 'SCROLL_MAINNET',
        etherscanChainId: 534352,
        simduneAlias: 'SCROLL',
        simduneChainId: 534352,
        simduneChainSlug: 'scroll',
        blocknativeAlias: 'SCROLL_MAINNET',
        blocknativeChainId: 534352,
        infuraSubdomain: 'scroll-mainnet'
    },
    {
        alias: 'ZKSYNC_MAINNET',
        chainId: 324,
        name: 'zkSync Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        etherscanAlias: 'ZKSYNC_MAINNET',
        etherscanChainId: 324,
        simduneAlias: 'ZKSYNC_ERA',
        simduneChainId: 324,
        simduneChainSlug: 'zksync',
        blocknativeAlias: 'ZKSYNC_MAINNET',
        blocknativeChainId: 324,
        infuraSubdomain: 'zksync-mainnet'
    },
    {
        alias: 'MANTLE_MAINNET',
        chainId: 5000,
        name: 'Mantle Mainnet',
        isTestnet: false,
        nativeCurrency: 'MNT',
        etherscanAlias: 'MANTLE_MAINNET',
        etherscanChainId: 5000,
        simduneAlias: 'MANTLE',
        simduneChainId: 5000,
        simduneChainSlug: 'mantle',
        blocknativeAlias: 'MANTLE_MAINNET',
        blocknativeChainId: 5000,
        infuraSubdomain: 'mantle-mainnet'
    },
    {
        alias: 'CELO_MAINNET',
        chainId: 42220,
        name: 'Celo Mainnet',
        isTestnet: false,
        nativeCurrency: 'CELO',
        etherscanAlias: 'CELO_MAINNET',
        etherscanChainId: 42220,
        simduneAlias: 'CELO_MAINNET',
        simduneChainId: 42220,
        simduneChainSlug: 'celo',
        moralisChainSlug: 'celo',
        moralisChainHex: '0xa4ec',
        infuraSubdomain: 'celo-mainnet',
        theGraphSlug: 'celo'
    },
    {
        alias: 'GNOSIS_MAINNET',
        chainId: 100,
        name: 'Gnosis',
        isTestnet: false,
        nativeCurrency: 'xDAI',
        etherscanAlias: 'GNOSIS_MAINNET',
        etherscanChainId: 100,
        simduneAlias: 'GNOSIS_CHAIN',
        simduneChainId: 100,
        simduneChainSlug: 'gnosis',
        moralisChainSlug: 'gnosis',
        moralisChainHex: '0x64',
        blocknativeAlias: 'GNOSIS_MAINNET',
        blocknativeChainId: 100
    },
    {
        alias: 'FANTOM_MAINNET',
        chainId: 250,
        name: 'Fantom Opera',
        isTestnet: false,
        nativeCurrency: 'FTM',
        simduneAlias: 'FANTOM',
        simduneChainId: 250,
        simduneChainSlug: 'fantom',
        moralisChainSlug: 'fantom',
        moralisChainHex: '0xfa',
        blocknativeAlias: 'FANTOM_MAINNET',
        blocknativeChainId: 250
    },
    {
        alias: 'CRONOS_MAINNET',
        chainId: 25,
        name: 'Cronos Mainnet',
        isTestnet: false,
        nativeCurrency: 'CRO',
        etherscanAlias: 'CRONOS_MAINNET',
        etherscanChainId: 25,
        moralisChainSlug: 'cronos',
        moralisChainHex: '0x19',
        blocknativeAlias: 'CRONOS_MAINNET',
        blocknativeChainId: 25
    },
    {
        alias: 'MOONBEAM_MAINNET',
        chainId: 1284,
        name: 'Moonbeam Mainnet',
        isTestnet: false,
        nativeCurrency: 'GLMR',
        etherscanAlias: 'MOONBEAM_MAINNET',
        etherscanChainId: 1284,
        moralisChainSlug: 'moonbeam',
        moralisChainHex: '0x504',
        blocknativeAlias: 'MOONBEAM_MAINNET',
        blocknativeChainId: 1284
    },
    {
        alias: 'MOONRIVER_MAINNET',
        chainId: 1285,
        name: 'Moonriver Mainnet',
        isTestnet: false,
        nativeCurrency: 'MOVR',
        etherscanAlias: 'MOONRIVER_MAINNET',
        etherscanChainId: 1285,
        moralisChainSlug: 'moonriver',
        moralisChainHex: '0x505'
    },
    {
        alias: 'ARBITRUM_NOVA_MAINNET',
        chainId: 42170,
        name: 'Arbitrum Nova Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        etherscanAlias: 'ARBITRUM_NOVA_MAINNET',
        etherscanChainId: 42170,
        simduneAlias: 'ARBITRUM_NOVA',
        simduneChainId: 42170,
        simduneChainSlug: 'arbitrum_nova'
    },
    {
        alias: 'BLAST_MAINNET',
        chainId: 81457,
        name: 'Blast Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        etherscanAlias: 'BLAST_MAINNET',
        etherscanChainId: 81457,
        simduneAlias: 'BLAST_MAINNET',
        simduneChainId: 81457,
        simduneChainSlug: 'blast',
        blocknativeAlias: 'BLAST_MAINNET',
        blocknativeChainId: 81457,
        theGraphSlug: 'blast'
    },
    {
        alias: 'SONIC_MAINNET',
        chainId: 146,
        name: 'Sonic Mainnet',
        isTestnet: false,
        nativeCurrency: 'S',
        etherscanAlias: 'SONIC_MAINNET',
        etherscanChainId: 146,
        simduneAlias: 'SONIC',
        simduneChainId: 146,
        simduneChainSlug: 'sonic'
    },
    {
        alias: 'BERACHAIN_MAINNET',
        chainId: 80094,
        name: 'Berachain Mainnet',
        isTestnet: false,
        nativeCurrency: 'BERA',
        etherscanAlias: 'BERACHAIN_MAINNET',
        etherscanChainId: 80094,
        simduneAlias: 'BERACHAIN',
        simduneChainId: 80094,
        simduneChainSlug: 'berachain',
        blocknativeAlias: 'BERACHAIN_MAINNET',
        blocknativeChainId: 80094
    },
    {
        alias: 'UNICHAIN_MAINNET',
        chainId: 130,
        name: 'Unichain Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        etherscanAlias: 'UNICHAIN_MAINNET',
        etherscanChainId: 130,
        simduneAlias: 'UNICHAIN',
        simduneChainId: 130,
        simduneChainSlug: 'unichain',
        blocknativeAlias: 'UNICHAIN_MAINNET',
        blocknativeChainId: 130
    },
    {
        alias: 'POLYGONZK_MAINNET',
        chainId: 1101,
        name: 'Polygon zkEVM Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        etherscanAlias: 'POLYGONZK_MAINNET',
        etherscanChainId: 1101,
        simduneAlias: 'ZKEVM',
        simduneChainId: 1101,
        simduneChainSlug: 'zkevm',
        blocknativeAlias: 'POLYGONZK_MAINNET',
        blocknativeChainId: 1101
    },
    {
        alias: 'FRAXTAL_MAINNET',
        chainId: 252,
        name: 'Fraxtal Mainnet',
        isTestnet: false,
        nativeCurrency: 'frxETH',
        etherscanAlias: 'FRAXTAL_MAINNET',
        etherscanChainId: 252,
        simduneAlias: 'FRAXTAL',
        simduneChainId: 252,
        simduneChainSlug: 'fraxtal',
        blocknativeAlias: 'FRAXTAL_MAINNET',
        blocknativeChainId: 252
    },
    {
        alias: 'BITTORRENT_MAINNET',
        chainId: 199,
        name: 'BitTorrent Chain Mainnet',
        isTestnet: false,
        nativeCurrency: 'BTT',
        etherscanAlias: 'BITTORRENT_MAINNET',
        etherscanChainId: 199
    },
    {
        alias: 'APECHAIN_MAINNET',
        chainId: 33139,
        name: 'ApeChain Mainnet',
        isTestnet: false,
        nativeCurrency: 'APE',
        etherscanAlias: 'APECHAIN_MAINNET',
        etherscanChainId: 33139,
        simduneAlias: 'APE_CHAIN',
        simduneChainId: 33139,
        simduneChainSlug: 'ape_chain'
    },
    {
        alias: 'ABSTRACT_MAINNET',
        chainId: 2741,
        name: 'Abstract Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        etherscanAlias: 'ABSTRACT_MAINNET',
        etherscanChainId: 2741,
        simduneAlias: 'ABSTRACT',
        simduneChainId: 2741,
        simduneChainSlug: 'abstract'
    },
    {
        alias: 'WORLD_MAINNET',
        chainId: 480,
        name: 'World Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        etherscanAlias: 'WORLD_MAINNET',
        etherscanChainId: 480,
        simduneAlias: 'WORLD',
        simduneChainId: 480,
        simduneChainSlug: 'world',
        blocknativeAlias: 'WORLDCHAIN_MAINNET',
        blocknativeChainId: 480
    },
    {
        alias: 'SWELLCHAIN_MAINNET',
        chainId: 1923,
        name: 'Swellchain Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        etherscanAlias: 'SWELLCHAIN_MAINNET',
        etherscanChainId: 1923,
        simduneAlias: 'SWELLCHAIN',
        simduneChainId: 1923,
        simduneChainSlug: 'swellchain'
    },
    {
        alias: 'TAIKO_MAINNET',
        chainId: 167000,
        name: 'Taiko Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        etherscanAlias: 'TAIKO_MAINNET',
        etherscanChainId: 167000,
        simduneAlias: 'TAIKO',
        simduneChainId: 167000,
        simduneChainSlug: 'taiko',
        blocknativeAlias: 'TAIKO_MAINNET',
        blocknativeChainId: 167000
    },
    {
        alias: 'SOPHON_MAINNET',
        chainId: 50104,
        name: 'Sophon Mainnet',
        isTestnet: false,
        nativeCurrency: 'SOPH',
        etherscanAlias: 'SOPHON_MAINNET',
        etherscanChainId: 50104,
        simduneAlias: 'SOPHON',
        simduneChainId: 50104,
        simduneChainSlug: 'sophon'
    },
    {
        alias: 'WEMIX_MAINNET',
        chainId: 1111,
        name: 'WEMIX3.0 Mainnet',
        isTestnet: false,
        nativeCurrency: 'WEMIX',
        etherscanAlias: 'WEMIX3_MAINNET',
        etherscanChainId: 1111,
        simduneAlias: 'WEMIX',
        simduneChainId: 1111,
        simduneChainSlug: 'wemix'
    },
    {
        alias: 'XAI_MAINNET',
        chainId: 660279,
        name: 'Xai Mainnet',
        isTestnet: false,
        nativeCurrency: 'XAI',
        etherscanAlias: 'XAI_MAINNET',
        etherscanChainId: 660279,
        simduneAlias: 'XAI',
        simduneChainId: 660279,
        simduneChainSlug: 'xai'
    },
    {
        alias: 'XINFIN_MAINNET',
        chainId: 50,
        name: 'XDC Mainnet',
        isTestnet: false,
        nativeCurrency: 'XDC',
        etherscanAlias: 'XINFIN_MAINNET',
        etherscanChainId: 50
    },
    {
        alias: 'MEMECORE_MAINNET',
        chainId: 4352,
        name: 'Memecore Mainnet',
        isTestnet: false,
        nativeCurrency: 'MEME',
        etherscanAlias: 'MEMECORE_MAINNET',
        etherscanChainId: 4352
    },
    {
        alias: 'PALM_MAINNET',
        chainId: 11297108109,
        name: 'Palm Mainnet',
        isTestnet: false,
        nativeCurrency: 'PALM',
        moralisChainSlug: 'palm',
        moralisChainHex: '0x2a15c308d',
        blocknativeAlias: 'PALM_MAINNET',
        blocknativeChainId: 11297108109
    },
    {
        alias: 'PULSECHAIN_MAINNET',
        chainId: 369,
        name: 'PulseChain Mainnet',
        isTestnet: false,
        nativeCurrency: 'PLS',
        moralisChainSlug: 'pulse',
        moralisChainHex: '0x171'
    },
    {
        alias: 'CHILIZ_MAINNET',
        chainId: 88888,
        name: 'Chiliz Mainnet',
        isTestnet: false,
        nativeCurrency: 'CHZ',
        moralisChainSlug: 'chiliz',
        moralisChainHex: '0x15b38',
        blocknativeAlias: 'CHILIZ_MAINNET',
        blocknativeChainId: 88888
    },
    {
        alias: 'FLOW_MAINNET',
        chainId: 747,
        name: 'Flow Mainnet',
        isTestnet: false,
        nativeCurrency: 'FLOW',
        simduneAlias: 'FLOW',
        simduneChainId: 747,
        simduneChainSlug: 'flow',
        moralisChainSlug: 'flow',
        moralisChainHex: '0x2eb'
    },
    {
        alias: 'RONIN_MAINNET',
        chainId: 2020,
        name: 'Ronin Mainnet',
        isTestnet: false,
        nativeCurrency: 'RON',
        simduneAlias: 'RONIN',
        simduneChainId: 2020,
        simduneChainSlug: 'ronin',
        moralisChainSlug: 'ronin',
        moralisChainHex: '0x7e4',
        blocknativeAlias: 'RONIN_MAINNET',
        blocknativeChainId: 2020
    },
    {
        alias: 'LISK_MAINNET',
        chainId: 1135,
        name: 'Lisk Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'LISK',
        simduneChainId: 1135,
        simduneChainSlug: 'lisk',
        moralisChainSlug: 'lisk',
        moralisChainHex: '0x46f',
        blocknativeAlias: 'LISK_MAINNET',
        blocknativeChainId: 1135
    },
    {
        alias: 'MODE_MAINNET',
        chainId: 34443,
        name: 'Mode Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'MODE',
        simduneChainId: 34443,
        simduneChainSlug: 'mode',
        blocknativeAlias: 'MODE_TESTNET',
        blocknativeChainId: 34443
    },
    {
        alias: 'METIS_MAINNET',
        chainId: 1088,
        name: 'Metis Mainnet',
        isTestnet: false,
        nativeCurrency: 'METIS',
        simduneAlias: 'METIS',
        simduneChainId: 1088,
        simduneChainSlug: 'metis',
        blocknativeAlias: 'METIS_MAINNET',
        blocknativeChainId: 1088
    },
    {
        alias: 'ZORA_MAINNET',
        chainId: 7777777,
        name: 'Zora Network',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'ZORA_NETWORK',
        simduneChainId: 7777777,
        simduneChainSlug: 'zora',
        blocknativeAlias: 'ZORA_MAINNET',
        blocknativeChainId: 7777777
    },
    {
        alias: 'BOBA_MAINNET',
        chainId: 288,
        name: 'Boba Network',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'BOBA_NETWORK',
        simduneChainId: 288,
        simduneChainSlug: 'boba'
    },
    {
        alias: 'MINT_MAINNET',
        chainId: 185,
        name: 'Mint Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'MINT_MAINNET',
        simduneChainId: 185,
        simduneChainSlug: 'mint'
    },
    {
        alias: 'DEGEN_MAINNET',
        chainId: 666666666,
        name: 'Degen Chain',
        isTestnet: false,
        nativeCurrency: 'DEGEN',
        simduneAlias: 'DEGEN_CHAIN',
        simduneChainId: 666666666,
        simduneChainSlug: 'degen'
    },
    {
        alias: 'ANCIENT8_MAINNET',
        chainId: 888888888,
        name: 'Ancient8',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'ANCIENT8',
        simduneChainId: 888888888,
        simduneChainSlug: 'ancient8'
    },
    {
        alias: 'KAIA_MAINNET',
        chainId: 8217,
        name: 'Kaia Mainnet',
        isTestnet: false,
        nativeCurrency: 'KAIA',
        simduneAlias: 'KAIA',
        simduneChainId: 8217,
        simduneChainSlug: 'kaia'
    },
    {
        alias: 'OPBNB_MAINNET',
        chainId: 204,
        name: 'opBNB Mainnet',
        isTestnet: false,
        nativeCurrency: 'BNB',
        simduneAlias: 'OPBNB',
        simduneChainId: 204,
        simduneChainSlug: 'opbnb',
        blocknativeAlias: 'OPBNB_MAINNET',
        blocknativeChainId: 204
    },
    {
        alias: 'BOB_MAINNET',
        chainId: 60808,
        name: 'BOB Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'BOB',
        simduneChainId: 60808,
        simduneChainSlug: 'bob',
        blocknativeAlias: 'BOB_MAINNET',
        blocknativeChainId: 60808
    },
    {
        alias: 'FLARE_MAINNET',
        chainId: 14,
        name: 'Flare Mainnet',
        isTestnet: false,
        nativeCurrency: 'FLR',
        simduneAlias: 'FLARE',
        simduneChainId: 14,
        simduneChainSlug: 'flare'
    },
    {
        alias: 'CYBER_MAINNET',
        chainId: 7560,
        name: 'Cyber Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'CYBER',
        simduneChainId: 7560,
        simduneChainSlug: 'cyber'
    },
    {
        alias: 'PROOF_OF_PLAY_MAINNET',
        chainId: 70700,
        name: 'Proof of Play',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'PROOF_OF_PLAY',
        simduneChainId: 70700,
        simduneChainSlug: 'proof_of_play'
    },
    {
        alias: 'PROOF_OF_PLAY_BOSS_MAINNET',
        chainId: 70701,
        name: 'Proof of Play Boss',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'PROOF_OF_PLAY_BOSS',
        simduneChainId: 70701,
        simduneChainSlug: 'proof_of_play_boss'
    },
    {
        alias: 'HYPER_EVM_MAINNET',
        chainId: 999,
        name: 'Hyper EVM',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'HYPER_EVM',
        simduneChainId: 999,
        simduneChainSlug: 'hyper_evm'
    },
    {
        alias: 'INK_MAINNET',
        chainId: 57073,
        name: 'Ink Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'INK',
        simduneChainId: 57073,
        simduneChainSlug: 'ink',
        blocknativeAlias: 'INK_MAINNET',
        blocknativeChainId: 57073
    },
    {
        alias: 'SEI_MAINNET',
        chainId: 1329,
        name: 'Sei Mainnet',
        isTestnet: false,
        nativeCurrency: 'SEI',
        simduneAlias: 'SEI',
        simduneChainId: 1329,
        simduneChainSlug: 'sei',
        blocknativeAlias: 'SEI_MAINNET',
        blocknativeChainId: 1329
    },
    {
        alias: 'SONEIUM_MAINNET',
        chainId: 1868,
        name: 'Soneium Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'SONEIUM',
        simduneChainId: 1868,
        simduneChainSlug: 'soneium',
        blocknativeAlias: 'SONEIUM_MAINNET',
        blocknativeChainId: 1868
    },
    {
        alias: 'SHAPE_MAINNET',
        chainId: 360,
        name: 'Shape Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'SHAPE',
        simduneChainId: 360,
        simduneChainSlug: 'shape'
    },
    {
        alias: 'REDSTONE_MAINNET',
        chainId: 690,
        name: 'Redstone Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'REDSTONE',
        simduneChainId: 690,
        simduneChainSlug: 'redstone'
    },
    {
        alias: 'RARI_MAINNET',
        chainId: 1380012617,
        name: 'RARI Chain',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'RARI',
        simduneChainId: 1380012617,
        simduneChainSlug: 'rari'
    },
    {
        alias: 'OMNI_MAINNET',
        chainId: 166,
        name: 'Omni Mainnet',
        isTestnet: false,
        nativeCurrency: 'OMNI',
        simduneAlias: 'OMNI',
        simduneChainId: 166,
        simduneChainSlug: 'omni'
    },
    {
        alias: 'CORN_MAINNET',
        chainId: 21000000,
        name: 'Corn Mainnet',
        isTestnet: false,
        nativeCurrency: 'CORN',
        simduneAlias: 'CORN',
        simduneChainId: 21000000,
        simduneChainSlug: 'corn'
    },
    {
        alias: 'B3_MAINNET',
        chainId: 8333,
        name: 'B3 Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'B3',
        simduneChainId: 8333,
        simduneChainSlug: 'b3'
    },
    {
        alias: 'HAM_MAINNET',
        chainId: 5112,
        name: 'Ham Chain',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'HAM_CHAIN',
        simduneChainId: 5112,
        simduneChainSlug: 'ham'
    },
    {
        alias: 'HYCHAIN_MAINNET',
        chainId: 2911,
        name: 'HYCHAIN Mainnet',
        isTestnet: false,
        nativeCurrency: 'TOPIA',
        simduneAlias: 'HYCHAIN',
        simduneChainId: 2911,
        simduneChainSlug: 'hychain'
    },
    {
        alias: 'FUNKICHAIN_MAINNET',
        chainId: 33979,
        name: 'Funkichain',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'FUNKICHAIN',
        simduneChainId: 33979,
        simduneChainSlug: 'funkichain'
    },
    {
        alias: 'FORMA_MAINNET',
        chainId: 984122,
        name: 'Forma Mainnet',
        isTestnet: false,
        nativeCurrency: 'TIA',
        simduneAlias: 'FORMA',
        simduneChainId: 984122,
        simduneChainSlug: 'forma'
    },
    {
        alias: 'SUPERPOSITION_MAINNET',
        chainId: 55244,
        name: 'Superposition',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'SUPERPOSITION',
        simduneChainId: 55244,
        simduneChainSlug: 'superposition'
    },
    {
        alias: 'SUPERSEED_MAINNET',
        chainId: 5330,
        name: 'Superseed',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'SUPERSEED',
        simduneChainId: 5330,
        simduneChainSlug: 'superseed'
    },
    {
        alias: 'ZERO_NETWORK_MAINNET',
        chainId: 543210,
        name: 'Zero Network',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'ZERO_NETWORK',
        simduneChainId: 543210,
        simduneChainSlug: 'zero_network'
    },
    {
        alias: 'TRON_MAINNET',
        chainId: 728126428,
        name: 'TRON Mainnet',
        isTestnet: false,
        nativeCurrency: 'TRX',
        simduneAlias: 'TRON',
        simduneChainId: 728126428,
        simduneChainSlug: 'tron'
    },
    {
        alias: 'RSK_MAINNET',
        chainId: 30,
        name: 'RSK Mainnet',
        isTestnet: false,
        nativeCurrency: 'RBTC',
        blocknativeAlias: 'RSK_MAINNET',
        blocknativeChainId: 30
    },
    {
        alias: 'IMMUTABLE_ZKEVM_MAINNET',
        chainId: 13371,
        name: 'Immutable zkEVM Mainnet',
        isTestnet: false,
        nativeCurrency: 'IMX',
        blocknativeAlias: 'IMMUTABLE_ZKEVM_MAINNET',
        blocknativeChainId: 13371
    },
    {
        alias: 'SNAXCHAIN_MAINNET',
        chainId: 2192,
        name: 'Snaxchain Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        blocknativeAlias: 'SNAXCHAIN_MAINNET',
        blocknativeChainId: 2192
    },
    {
        alias: 'STORY_MAINNET',
        chainId: 1514,
        name: 'Story Mainnet',
        isTestnet: false,
        nativeCurrency: 'IP',
        blocknativeAlias: 'STORY_MAINNET',
        blocknativeChainId: 1514
    },
    {
        alias: 'ZETACHAIN_MAINNET',
        chainId: 7000,
        name: 'ZetaChain Mainnet',
        isTestnet: false,
        nativeCurrency: 'ZETA',
        blocknativeAlias: 'ZETACHAIN_MAINNET',
        blocknativeChainId: 7000
    },
    {
        alias: 'BITCOIN_MAINNET',
        chainId: 0,
        name: 'Bitcoin Mainnet',
        isTestnet: false,
        nativeCurrency: 'BTC',
        blocknativeAlias: 'BITCOIN_MAINNET',
        blocknativeChainId: 0
    },
    {
        alias: 'LENS_MAINNET',
        chainId: 232,
        name: 'Lens Mainnet',
        isTestnet: false,
        nativeCurrency: 'GHO',
        simduneAlias: 'LENS',
        simduneChainId: 232,
        simduneChainSlug: 'lens'
    },
    {
        alias: 'PLUME_MAINNET',
        chainId: 98866,
        name: 'Plume Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'PLUME',
        simduneChainId: 98866,
        simduneChainSlug: 'plume'
    },
    {
        alias: 'HEMI_MAINNET',
        chainId: 43111,
        name: 'Hemi Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'HEMI',
        simduneChainId: 43111,
        simduneChainSlug: 'hemi'
    },
    {
        alias: 'KATANA_MAINNET',
        chainId: 747474,
        name: 'Katana Mainnet',
        isTestnet: false,
        nativeCurrency: 'ETH',
        simduneAlias: 'KATANA',
        simduneChainId: 747474,
        simduneChainSlug: 'katana'
    },
    {
        alias: 'SOMNIA_MAINNET',
        chainId: 5031,
        name: 'Somnia Mainnet',
        isTestnet: false,
        nativeCurrency: 'STT',
        simduneAlias: 'SOMNIA',
        simduneChainId: 5031,
        simduneChainSlug: 'somnia'
    },
    {
        alias: 'TAC_MAINNET',
        chainId: 239,
        name: 'TAC Mainnet',
        isTestnet: false,
        nativeCurrency: 'TAC',
        simduneAlias: 'TAC',
        simduneChainId: 239,
        simduneChainSlug: 'tac'
    },

    // ============================================================
    // TESTNETS
    // ============================================================
    {
        alias: 'SEPOLIA_TESTNET',
        chainId: 11155111,
        name: 'Sepolia Testnet',
        isTestnet: true,
        nativeCurrency: 'ETH',
        etherscanAlias: 'SEPOLIA_TESTNET',
        etherscanChainId: 11155111,
        simduneAlias: 'ETHEREUM_SEPOLIA',
        simduneChainId: 11155111,
        simduneChainSlug: 'sepolia',
        moralisChainSlug: 'sepolia',
        moralisChainHex: '0xaa36a7',
        infuraSubdomain: 'sepolia'
    },
    {
        alias: 'HOLESKY_TESTNET',
        chainId: 17000,
        name: 'Holesky Testnet',
        isTestnet: true,
        nativeCurrency: 'ETH',
        etherscanAlias: 'HOLESKY_TESTNET',
        etherscanChainId: 17000,
        moralisChainSlug: 'holesky',
        moralisChainHex: '0x4268'
    },
    {
        alias: 'BASE_SEPOLIA_TESTNET',
        chainId: 84532,
        name: 'Base Sepolia Testnet',
        isTestnet: true,
        nativeCurrency: 'ETH',
        etherscanAlias: 'BASE_SEPOLIA_TESTNET',
        etherscanChainId: 84532,
        simduneAlias: 'BASE_SEPOLIA',
        simduneChainId: 84532,
        simduneChainSlug: 'base_sepolia',
        moralisChainSlug: 'base sepolia',
        moralisChainHex: '0x14a34'
    },
    {
        alias: 'POLYGON_AMOY_TESTNET',
        chainId: 80002,
        name: 'Polygon Amoy Testnet',
        isTestnet: true,
        nativeCurrency: 'POL',
        etherscanAlias: 'POLYGON_AMOY_TESTNET',
        etherscanChainId: 80002,
        moralisChainSlug: 'polygon amoy',
        moralisChainHex: '0x13882'
    },
    {
        alias: 'BINANCE_TESTNET',
        chainId: 97,
        name: 'BNB Smart Chain Testnet',
        isTestnet: true,
        nativeCurrency: 'tBNB',
        etherscanAlias: 'BINANCE_TESTNET',
        etherscanChainId: 97,
        moralisChainSlug: 'bsc testnet',
        moralisChainHex: '0x61'
    },
    {
        alias: 'AVALANCHE_FUJI_TESTNET',
        chainId: 43113,
        name: 'Avalanche Fuji Testnet',
        isTestnet: true,
        nativeCurrency: 'AVAX',
        etherscanAlias: 'AVALANCHE_FUJI_TESTNET',
        etherscanChainId: 43113,
        simduneAlias: 'AVALANCHE_FUJI',
        simduneChainId: 43113,
        simduneChainSlug: 'avalanche_fuji'
    },
    {
        alias: 'ARBITRUM_SEPOLIA_TESTNET',
        chainId: 421614,
        name: 'Arbitrum Sepolia Testnet',
        isTestnet: true,
        nativeCurrency: 'ETH',
        etherscanAlias: 'ARBITRUM_SEPOLIA_TESTNET',
        etherscanChainId: 421614
    },
    {
        alias: 'OPTIMISM_SEPOLIA_TESTNET',
        chainId: 11155420,
        name: 'OP Sepolia Testnet',
        isTestnet: true,
        nativeCurrency: 'ETH',
        etherscanAlias: 'OPTIMISN_SEPOLIA_TESTNET',
        etherscanChainId: 11155420
    },
    {
        alias: 'LINEA_SEPOLIA_TESTNET',
        chainId: 59141,
        name: 'Linea Sepolia Testnet',
        isTestnet: true,
        nativeCurrency: 'ETH',
        etherscanAlias: 'LINEA_SEPOLIA_TESTNET',
        etherscanChainId: 59141,
        moralisChainSlug: 'linea sepolia',
        moralisChainHex: '0xe705'
    },
    {
        alias: 'SCROLL_SEPOLIA_TESTNET',
        chainId: 534351,
        name: 'Scroll Sepolia Testnet',
        isTestnet: true,
        nativeCurrency: 'ETH',
        etherscanAlias: 'SCROLL_SEPOLIA_TESTNET',
        etherscanChainId: 534351
    },
    {
        alias: 'ZKSYNC_SEPOLIA_TESTNET',
        chainId: 300,
        name: 'zkSync Sepolia Testnet',
        isTestnet: true,
        nativeCurrency: 'ETH',
        etherscanAlias: 'ZKSYNC_SEPOLIA_TESTNET',
        etherscanChainId: 300
    },
    {
        alias: 'ABSTRACT_SEPOLIA_TESTNET',
        chainId: 11124,
        name: 'Abstract Sepolia Testnet',
        isTestnet: true,
        nativeCurrency: 'ETH',
        etherscanAlias: 'ABSTRACT_SEPOLIA_TESTNET',
        etherscanChainId: 11124
    },
    {
        alias: 'BLAST_SEPOLIA_TESTNET',
        chainId: 168587773,
        name: 'Blast Sepolia Testnet',
        isTestnet: true,
        nativeCurrency: 'ETH',
        etherscanAlias: 'BLAST_SEPOLIA_TESTNET',
        etherscanChainId: 168587773
    },
    {
        alias: 'BERACHAIN_BEPOLIA_TESTNET',
        chainId: 80069,
        name: 'Berachain Bepolia Testnet',
        isTestnet: true,
        nativeCurrency: 'BERA',
        etherscanAlias: 'BERACHAIN_BEPOLIA_TESTNET',
        etherscanChainId: 80069
    },
    {
        alias: 'BITTORRENT_TESTNET',
        chainId: 1028,
        name: 'BitTorrent Chain Testnet',
        isTestnet: true,
        nativeCurrency: 'BTT',
        etherscanAlias: 'BITTORRENT_TESTNET',
        etherscanChainId: 1028
    },
    {
        alias: 'CELO_ALFAJORES_TESTNET',
        chainId: 44787,
        name: 'Celo Alfajores Testnet',
        isTestnet: true,
        nativeCurrency: 'CELO',
        etherscanAlias: 'CELO_ALFAJORES_TESTNET',
        etherscanChainId: 44787
    },
    {
        alias: 'FRAXTAL_TESTNET',
        chainId: 2522,
        name: 'Fraxtal Testnet',
        isTestnet: true,
        nativeCurrency: 'frxETH',
        etherscanAlias: 'FRAXTAL_TESTNET',
        etherscanChainId: 2522
    },
    {
        alias: 'MANTLE_SEPOLIA_TESTNET',
        chainId: 5003,
        name: 'Mantle Sepolia Testnet',
        isTestnet: true,
        nativeCurrency: 'MNT',
        etherscanAlias: 'MANTLE_SEPOLIA_TESTNET',
        etherscanChainId: 5003
    },
    {
        alias: 'MEMECORE_TESTNET',
        chainId: 43521,
        name: 'Memecore Testnet',
        isTestnet: true,
        nativeCurrency: 'MEME',
        etherscanAlias: 'MEMECORE_TESTNET',
        etherscanChainId: 43521
    },
    {
        alias: 'MOONBASE_ALPHA_TESTNET',
        chainId: 1287,
        name: 'Moonbase Alpha Testnet',
        isTestnet: true,
        nativeCurrency: 'DEV',
        etherscanAlias: 'MOONBASE_ALPHA_TESTNET',
        etherscanChainId: 1287,
        moralisChainSlug: 'moonbase',
        moralisChainHex: '0x507'
    },
    {
        alias: 'POLYGONZK_CARDONA_TESTNET',
        chainId: 2442,
        name: 'Polygon zkEVM Cardona Testnet',
        isTestnet: true,
        nativeCurrency: 'ETH',
        etherscanAlias: 'POLYGONZK_CARDONA_TESTNET',
        etherscanChainId: 2442
    },
    {
        alias: 'SONIC_BLAZE_TESTNET',
        chainId: 57054,
        name: 'Sonic Blaze Testnet',
        isTestnet: true,
        nativeCurrency: 'S',
        etherscanAlias: 'SONIC_BLAZE_TESTNET',
        etherscanChainId: 57054
    },
    {
        alias: 'SOPHON_SEPOLIA_TESTNET',
        chainId: 531050104,
        name: 'Sophon Sepolia Testnet',
        isTestnet: true,
        nativeCurrency: 'SOPH',
        etherscanAlias: 'SOPHON_SEPOLIA_TESTNET',
        etherscanChainId: 531050104
    },
    {
        alias: 'SWELLCHAIN_TESTNET',
        chainId: 1924,
        name: 'Swellchain Testnet',
        isTestnet: true,
        nativeCurrency: 'ETH',
        etherscanAlias: 'SWELLCHAIN_TESTNET',
        etherscanChainId: 1924
    },
    {
        alias: 'TAIKO_HEKLA_TESTNET',
        chainId: 167009,
        name: 'Taiko Hekla L2 Testnet',
        isTestnet: true,
        nativeCurrency: 'ETH',
        etherscanAlias: 'TAIKO_HEKLA_L2_TESTNET',
        etherscanChainId: 167009
    },
    {
        alias: 'UNICHAIN_SEPOLIA_TESTNET',
        chainId: 1301,
        name: 'Unichain Sepolia Testnet',
        isTestnet: true,
        nativeCurrency: 'ETH',
        etherscanAlias: 'UNICHAIN_SEPOLIA_TESTNET',
        etherscanChainId: 1301
    },
    {
        alias: 'WEMIX_TESTNET',
        chainId: 1112,
        name: 'WEMIX3.0 Testnet',
        isTestnet: true,
        nativeCurrency: 'WEMIX',
        etherscanAlias: 'WEMIX3_TESTNET',
        etherscanChainId: 1112
    },
    {
        alias: 'WORLD_SEPOLIA_TESTNET',
        chainId: 4801,
        name: 'World Sepolia Testnet',
        isTestnet: true,
        nativeCurrency: 'ETH',
        etherscanAlias: 'WORLD_SEPOLIA_TESTNET',
        etherscanChainId: 4801
    },
    {
        alias: 'XAI_SEPOLIA_TESTNET',
        chainId: 37714555429,
        name: 'Xai Sepolia Testnet',
        isTestnet: true,
        nativeCurrency: 'XAI',
        etherscanAlias: 'XAI_SEPOLIA_TESTNET',
        etherscanChainId: 37714555429
    },
    {
        alias: 'XINFIN_TESTNET',
        chainId: 51,
        name: 'XDC Apothem Testnet',
        isTestnet: true,
        nativeCurrency: 'XDC',
        etherscanAlias: 'XINFIN_TESTNET',
        etherscanChainId: 51
    },
    {
        alias: 'APECHAIN_CURTIS_TESTNET',
        chainId: 33111,
        name: 'ApeChain Curtis Testnet',
        isTestnet: true,
        nativeCurrency: 'APE',
        etherscanAlias: 'APECHAIN_CURTIS_TESTNET',
        etherscanChainId: 33111
    },
    {
        alias: 'GNOSIS_TESTNET',
        chainId: 10200,
        name: 'Gnosis Chiado Testnet',
        isTestnet: true,
        nativeCurrency: 'xDAI',
        moralisChainSlug: 'gnosis testnet',
        moralisChainHex: '0x27d8'
    },
    {
        alias: 'CHILIZ_TESTNET',
        chainId: 88882,
        name: 'Chiliz Spicy Testnet',
        isTestnet: true,
        nativeCurrency: 'CHZ',
        moralisChainSlug: 'chiliz testnet',
        moralisChainHex: '0x15b32'
    },
    {
        alias: 'FLOW_TESTNET',
        chainId: 545,
        name: 'Flow Testnet',
        isTestnet: true,
        nativeCurrency: 'FLOW',
        moralisChainSlug: 'flow-testnet',
        moralisChainHex: '0x221'
    },
    {
        alias: 'RONIN_TESTNET',
        chainId: 2021,
        name: 'Ronin Saigon Testnet',
        isTestnet: true,
        nativeCurrency: 'RON',
        moralisChainSlug: 'ronin-testnet',
        moralisChainHex: '0x7e5'
    },
    {
        alias: 'LISK_SEPOLIA_TESTNET',
        chainId: 4202,
        name: 'Lisk Sepolia Testnet',
        isTestnet: true,
        nativeCurrency: 'ETH',
        moralisChainSlug: 'lisk-sepolia',
        moralisChainHex: '0x106a'
    },
    {
        alias: 'LENS_SEPOLIA_TESTNET',
        chainId: 37111,
        name: 'Lens Sepolia Testnet',
        isTestnet: true,
        nativeCurrency: 'GHO',
        blocknativeAlias: 'LENS_SEPOLIA_TESTNET',
        blocknativeChainId: 37111
    },
    {
        alias: 'MONAD_TESTNET',
        chainId: 10143,
        name: 'Monad Testnet',
        isTestnet: true,
        nativeCurrency: 'MON',
        simduneAlias: 'MONAD_TESTNET',
        simduneChainId: 10143,
        simduneChainSlug: 'monad_testnet'
    }
]


export { EVM_CHAINS }
