name: Run Tests with Coverage and Update README

on:
  push:
    branches:
      - main
# optional sinnvoll: auch PRs prüfen
# on:
#   push:
#   pull_request:

permissions:
  contents: write
  id-token: write   # << nötig für OIDC

jobs:
  test-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests (with coverage)
        run: npm run test:coverage:src

      - name: Upload coverage to Codecov (OIDC)
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          files: ./coverage/lcov.info      # Jest legt diese Datei standardmäßig an
          fail_ci_if_error: true
          flags: unittests
        # optional: auch hochladen, wenn Tests fehlschlagen
        # if: ${{ always() }}

      - name: Generate README
        run: node ./.github/workflows/generate-readme/index.mjs

      - name: Commit and Push README Changes
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "a6b8"
          git add .
          if ! git diff --cached --exit-code; then
            git commit -m "Update README with latest schema changes 🤖"
            git push
          else
            echo "No README changes to commit"
          fi